name        : diffutils
version     : 3.3
release     : 5
source      :
    - http://ftp.gnu.org/gnu/diffutils/diffutils-3.3.tar.xz : a25e89a8ab65fded1731e4186be1bb25cda967834b6df973599cdcd5abdfc19c
homepage    : http://www.gnu.org/software/diffutils/
license     :
    - GPL-2.0
summary     : The Diffutils package contains programs that show the differences between files or directories
description : |
    The Diffutils package contains programs that show the differences between files or directories.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
