name       : diffutils
version    : 3.5
release    : 6
source     :
    - https://ftp.gnu.org/gnu/diffutils/diffutils-3.5.tar.xz : dad398ccd5b9faca6b0ab219a036453f62a602a56203ac659b43e889bec35533
homepage   : http://www.gnu.org/software/diffutils/
component  : system.devel
license    :
    - GPL-2.0
summary    : The Diffutils package contains programs that show the differences between files or directories
description: |
    The Diffutils package contains programs that show the differences between files or directories.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
