name       : diffutils
version    : 3.7
release    : 10
source     :
    - https://ftp.gnu.org/gnu/diffutils/diffutils-3.7.tar.xz : b3a7a6221c3dc916085f0d205abf6b8e1ba443d4dd965118da364a1dc1cb3a26
homepage   : https://www.gnu.org/software/diffutils/
component  : system.devel
license    : GPL-2.0-or-later
summary    : The Diffutils package contains programs that show the differences between
    files or directories
description: |
    The Diffutils package contains programs that show the differences between files or directories.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-colors-test.patch
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
