name       : diffutils
version    : '3.8'
release    : 11
source     :
    - https://ftp.gnu.org/gnu/diffutils/diffutils-3.8.tar.xz : a6bdd7d1b31266d11c4f4de6c1b748d4607ab0231af5188fc2533d0ae2438fec
homepage   : https://www.gnu.org/software/diffutils/
component  : system.devel
license    : GPL-2.0-or-later
summary    : The Diffutils package contains programs that show the differences between files or directories
description: |
    The Diffutils package contains programs that show the differences between files or directories.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-colors-test.patch
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
